#include "lib/regs.h"

// So that the flags are included
#undef CHECK_MEM

#include "lib/fuzzing_value_map.h"

int main() {
    printf("# Generated by print-fuzzing-value-map.c\n\nimport pyutils.config as config\n\n");
    printf("filler_64 = 0x%lx\n\n", filler_64);
    printf("fuzzing_value_map_gp = [\n");
    for (unsigned i = 0; i < fuzzing_value_map_gp_size/sizeof(fuzzing_value_map_gp[0]); i++) {
        printf("  0x%lx,\n", fuzzing_value_map_gp[i]);
    }
    printf("]\n\nfuzzing_value_map_fp = [\n");
    for (unsigned i = 0; i < fuzzing_value_map_fp_size/sizeof(fuzzing_value_map_fp[0]); i++) {
        printf("  0x%lx,\n", fuzzing_value_map_fp[i].u);
    }
    printf("]");
}
